In [21]:
import torch
import numpy
t = torch.tensor([[.94, .89, .14, .13], 
                  [.23, .01, .25, .15],
                  [.33, .23, .12, 1-2e-3]])
rt = t > .5

a = numpy.array(t)
ra = a > .5

print(rt)

tensor([[ True,  True, False, False],
        [False, False, False, False],
        [False, False, False,  True]])


In [28]:
ct = t.clamp(min=0.2,max=0.5)
print(ct)

ca = a.clip(min=0.2,max=0.5)
print(ca)
print(ca[1,2],ca[1][2],ca[[[0,1],[2,3]]])

tensor([[0.5000, 0.5000, 0.2000, 0.2000],
        [0.2300, 0.2000, 0.2500, 0.2000],
        [0.3300, 0.2300, 0.2000, 0.5000]])
[[0.5  0.5  0.2  0.2 ]
 [0.23 0.2  0.25 0.2 ]
 [0.33 0.23 0.2  0.5 ]]
0.25 0.25 [0.2 0.2]


/home/cver/anaconda3/envs/lcx/lib/python3.7/site-packages/ipykernel_launcher.py:6: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  


In [23]:
jt = ct == .2
print(jt)
ja = ca == .2
print(ja)

tensor([[False, False,  True,  True],
        [False,  True, False,  True],
        [False, False,  True, False]])
[[False False  True  True]
 [False  True False  True]
 [False False  True False]]


In [24]:
print(t[jt])
print(a[ja])

tensor([0.1400, 0.1300, 0.0100, 0.1500, 0.1200])
[0.14 0.13 0.01 0.15 0.12]


In [20]:
1-2e-3

0.998

In [42]:
import numpy as np
arr = np.array(([[0.5100, 0.5200, 0.2100, 0.2200],
                 [0.2300, 0.2400, 0.2500, 0.2600],
                 [0.3300, 0.2700, 0.2800, 0.5300]]))
ind = np.array([[0,2],[1,2]])
ind2 = np.array([[1,1],[0,0]])
print('1',arr[ind])
print('2',arr[ind2])

print(arr[ind,ind2])
# print(arr[ind][ind2])

1 [[[0.51 0.52 0.21 0.22]
  [0.33 0.27 0.28 0.53]]

 [[0.23 0.24 0.25 0.26]
  [0.33 0.27 0.28 0.53]]]
2 [[[0.23 0.24 0.25 0.26]
  [0.23 0.24 0.25 0.26]]

 [[0.51 0.52 0.21 0.22]
  [0.51 0.52 0.21 0.22]]]
[[0.52 0.27]
 [0.23 0.33]]


In [49]:
import torch,math
a = torch.exp(torch.tensor([0, 1.]))
print(a)
m = math.log(2.)
print(m)
b = torch.exp(torch.tensor([m]))
print(b)

tensor([1.0000, 2.7183])
0.6931471805599453
tensor([2.])


In [51]:
import torch.tensor as tensor
a = tensor([[1, 2, 0, 3],
            [2, 1, 0, 3],
            [2, 0, 3, 1]])

b = tensor([[1, 1, 1, 1],
            [2, 2, 2, 2],
            [3, 3, 3, 3]])

c = a < b
print(c)

tensor([[False, False,  True, False],
        [False,  True,  True, False],
        [ True,  True, False,  True]])


In [151]:
import torch
# torch.cuda.manual_seed_all(10) # GPU
# gen = torch.Generator()
# gen.manual_seed(0)
gen = torch.manual_seed(0) # global
a = torch.randperm(10,generator = gen)
b = torch.randperm(10,generator = gen)
c = torch.randperm(10)
print(a,'\n',b,'\n',c)
# print(type(gen))

tensor([4, 1, 7, 5, 3, 9, 0, 8, 6, 2]) 
 tensor([3, 9, 4, 2, 7, 8, 6, 0, 5, 1]) 
 tensor([4, 0, 8, 5, 9, 1, 6, 3, 7, 2])


In [147]:
tensor([4, 1, 7, 5, 3, 9, 0, 8, 6, 2]) 
tensor([3, 9, 4, 2, 7, 8, 6, 0, 5, 1]) 
tensor([4, 0, 8, 5, 9, 1, 6, 3, 7, 2])

tensor([4, 0, 8, 5, 9, 1, 6, 3, 7, 2])

In [134]:
from random_test import rand_test as rt
import torch
torch.manual_seed(0)
print(rt(),'\n',rt())


tensor([4, 1, 7, 5, 3, 9, 0, 8, 6, 2]) 
 tensor([3, 9, 4, 2, 7, 8, 6, 0, 5, 1])


In [137]:
import random
import torch
import numpy as np
print(random.random())
print(torch.randperm(10))

0.13436424411240122


In [142]:
torch.manual_seed(42)
torch.cuda.manual_seed(42)
np.random.seed(42)
random.seed(42)
torch.backends.cudnn.deterministic=True

features = torch.randn(2,5)
print(features)

tensor([[ 0.3367,  0.1288,  0.2345,  0.2303, -1.1229],
        [-0.1863,  2.2082, -0.6380,  0.4617,  0.2674]])


In [152]:
a = [796, 557, 960, 1040, 58, 1047, 128, 620, 649, 624, 843, 577, 454, 260, 221, 984, 1027, 245, 544, 699, 388, 820, 810, 879, 1005, 496, 69, 480, 885, 848, 852, 515, 898, 980, 88, 130, 560, 499, 584, 350, 1002, 355, 119, 778, 750, 688, 921, 723, 774, 563, 273, 423, 416, 59, 562, 682, 6, 681, 445, 300, 605, 658, 274, 533, 728, 638, 546, 881, 16, 858, 867, 71, 976, 492, 38, 207, 806, 433, 981, 176, 374, 415, 698, 595, 765, 279, 100, 178, 880, 133, 356, 109, 397, 444, 286, 958, 954, 700, 601, 590, 854, 572, 113, 108, 742, 591, 171, 992, 667, 376, 161, 964, 797, 905, 619, 690, 464, 44, 961, 238, 859, 317, 358, 395, 459, 160, 589, 694, 162, 118, 719, 732, 1006, 784, 977, 718, 631, 413, 112, 709, 271, 993, 313, 1046, 989, 671, 80, 998, 692, 769, 35, 328, 163, 230, 529, 170, 244, 527, 447, 739, 538, 361, 986, 549, 962, 106, 955, 660, 231, 357, 404, 209, 665, 191, 999, 988, 487, 653, 926, 29, 401, 727, 1013, 495, 57, 36, 817, 203, 1014, 972, 749, 746, 794, 1021, 169, 701, 614, 166, 525, 174, 386, 227, 821, 335, 98, 666, 754, 938, 555, 214, 22, 52, 425, 1038, 223, 995, 45, 1030, 724, 578, 807, 85, 740, 1004, 311, 451, 628, 635, 290, 725, 125, 836, 175, 866, 440, 25, 146, 801, 362, 49, 262, 626, 636, 3, 332, 186, 800, 199, 84, 637, 70, 102, 837, 872, 353, 143, 530, 318, 971, 50, 173, 24, 764, 664, 730, 766, 334, 760, 152, 678, 4, 567, 73, 134, 331, 1008, 710, 28, 20, 448, 78, 27, 523, 379, 316, 912, 855, 1011, 920, 458, 1033, 339, 650, 420, 456, 326, 863, 1034, 851, 706, 598, 894, 90, 959, 629, 208, 430, 1056, 450, 306, 104, 592, 233, 66, 856, 579, 91, 783, 345, 414, 672, 870, 641, 860, 919, 360, 457, 804, 147, 436, 752, 494, 1010, 219, 421, 627, 556, 310, 849, 10, 826, 950, 321, 5, 60, 891, 941, 168, 903, 382, 695, 7, 973, 23, 1023, 827, 1036, 115, 226, 489, 40, 786, 831, 419, 1042, 991, 342, 465, 536, 618, 264, 19, 182, 438, 647, 1053, 864, 18, 674, 307, 644, 399, 751, 126, 951, 901, 915, 120, 257, 61, 2, 12, 965, 439, 947, 424, 21, 693, 600, 453, 846, 250, 676, 407, 304, 150, 472, 734, 1024, 610, 869, 818, 802, 756, 585, 890, 466, 183, 349, 211, 808, 773, 336, 37, 772, 907, 482, 17, 13, 609, 89, 935, 299, 582, 484, 467, 978, 943, 400, 359, 325, 148, 594, 1007, 1039, 117, 383, 344, 835, 485, 285, 970, 468, 55, 703, 937, 210, 327, 737, 668, 1043, 329, 1041, 1012, 944, 493, 94, 87, 588, 815, 558, 561, 266, 985, 763, 768, 1058, 1029, 933, 64, 713, 531, 365, 303, 575, 437, 46, 508, 393, 165, 744, 391, 135, 1048, 116, 124, 378, 528, 916, 673, 874, 212, 301, 517, 932, 1017, 781, 825, 1050, 202, 953, 463, 77, 654, 0, 256, 1035, 377, 461, 197, 788, 248, 375, 72, 568, 844, 159, 1054, 616, 151, 882, 717, 410, 613, 237, 281, 9, 736, 735, 829, 685, 497, 267, 634, 1020, 720, 770, 822, 677, 1031, 368, 888, 868, 573, 340, 643, 889, 928, 483, 341, 511, 172, 294, 145, 996, 282, 1001, 287, 93, 952, 333, 904, 372, 405, 853, 155, 721, 776, 691, 745, 74, 542, 272, 566, 799, 278, 129, 277, 942, 696, 370, 841, 261, 123, 537, 236, 899, 352, 121, 812, 265, 761, 684, 662, 63, 757, 670, 490, 702, 330, 308, 322, 990, 187, 949, 298, 552, 103, 452, 892, 687, 99, 426, 200, 762, 526, 249, 633, 657, 488, 897, 247, 158, 180, 65, 780, 931, 708, 845, 295, 884, 347, 967, 86, 645, 816, 412, 139, 648, 320, 532, 622, 675, 697, 832, 603, 1055, 181, 95, 213, 48, 486, 559, 576, 607, 738, 309, 232, 280, 522, 42, 198, 731, 798, 503, 269, 873, 312, 541, 987, 26, 966, 539, 474, 177, 390, 805, 283, 194, 1018, 469, 189, 380, 481, 217, 759, 373, 599, 394, 132, 957, 994, 337, 409, 714, 929, 792, 969, 297, 136, 939, 193, 319, 679, 771, 871, 354, 296, 606, 432, 255, 470, 847, 922, 646, 656, 216, 498, 449, 946, 824, 441, 910, 292, 505, 363, 33, 779, 293, 31, 712, 502, 945, 446, 917, 56, 982, 914, 140, 554, 574, 930, 602, 114, 1059, 803, 663, 785, 833, 711, 963, 893, 639, 392, 909, 510, 680, 840, 367, 154, 418, 67, 521, 659, 570, 758, 979, 1022, 651, 252, 608, 1032, 442, 587, 479, 1019, 253, 291, 551, 704, 652, 348, 195, 509, 813, 478, 204, 142, 225, 398, 553, 876, 886, 625, 705, 878, 259, 715, 767, 240, 381, 243, 149, 369, 53, 68, 411, 612, 512, 975, 141, 1051, 621, 789, 513, 62, 455, 276, 661, 475, 105, 1037, 908, 122, 535, 795, 43, 580, 716, 51, 167, 862, 462, 30, 839, 153, 428, 1025, 491, 911, 581, 936, 875, 81, 258, 814, 385, 15, 923, 215, 96, 545, 403, 611, 179, 593, 235, 387, 220, 655, 550, 604, 1044, 434, 314, 632, 471, 583, 206, 8, 518, 188, 110, 689, 431, 865, 234, 842, 263, 422, 895, 429, 640, 819, 185, 32, 565, 246, 254, 473, 617, 41, 79, 940, 500, 506, 741, 218, 137, 476, 460, 1016, 997, 302, 111, 1045, 275, 828, 1015, 524, 251, 968, 548, 164, 242, 343, 974, 924, 1028, 850, 288, 205, 284, 1, 82, 743, 351, 790, 315, 1026, 239, 241, 34, 427, 630, 364, 417, 443, 623, 1000, 983, 14, 507, 669, 504, 131, 371, 883, 144, 338, 927, 547, 346, 396, 755, 54, 902, 896, 791, 777, 782, 571, 138, 747, 11, 156, 838, 39, 569, 534, 733, 192, 92, 729, 1049, 564, 435, 753, 1052, 201, 726, 196, 748, 184, 830, 516, 900, 519, 707, 1009, 75, 586, 934, 956, 1003, 305, 384, 887, 107, 101, 913, 324, 811, 477, 877, 834, 683, 597, 289, 222, 861, 514, 47, 809, 389, 157, 402, 1057, 408, 229, 268, 543, 722, 686, 224, 642, 793, 857, 906, 501, 228, 366, 76, 270, 540, 948, 596, 823, 615, 323, 520, 97, 127, 406, 925, 918, 190, 787, 83, 775]
b = [796, 557, 960, 1040, 58, 1047, 128, 620, 649, 624, 843, 577, 454, 260, 221, 984, 1027, 245, 544, 699, 388, 820, 810, 879, 1005, 496, 69, 480, 885, 848, 852, 515, 898, 980, 88, 130, 560, 499, 584, 350, 1002, 355, 119, 778, 750, 688, 921, 723, 774, 563, 273, 423, 416, 59, 562, 682, 6, 681, 445, 300, 605, 658, 274, 533, 728, 638, 546, 881, 16, 858, 867, 71, 976, 492, 38, 207, 806, 433, 981, 176, 374, 415, 698, 595, 765, 279, 100, 178, 880, 133, 356, 109, 397, 444, 286, 958, 954, 700, 601, 590, 854, 572, 113, 108, 742, 591, 171, 992, 667, 376, 161, 964, 797, 905, 619, 690, 464, 44, 961, 238, 859, 317, 358, 395, 459, 160, 589, 694, 162, 118, 719, 732, 1006, 784, 977, 718, 631, 413, 112, 709, 271, 993, 313, 1046, 989, 671, 80, 998, 692, 769, 35, 328, 163, 230, 529, 170, 244, 527, 447, 739, 538, 361, 986, 549, 962, 106, 955, 660, 231, 357, 404, 209, 665, 191, 999, 988, 487, 653, 926, 29, 401, 727, 1013, 495, 57, 36, 817, 203, 1014, 972, 749, 746, 794, 1021, 169, 701, 614, 166, 525, 174, 386, 227, 821, 335, 98, 666, 754, 938, 555, 214, 22, 52, 425, 1038, 223, 995, 45, 1030, 724, 578, 807, 85, 740, 1004, 311, 451, 628, 635, 290, 725, 125, 836, 175, 866, 440, 25, 146, 801, 362, 49, 262, 626, 636, 3, 332, 186, 800, 199, 84, 637, 70, 102, 837, 872, 353, 143, 530, 318, 971, 50, 173, 24, 764, 664, 730, 766, 334, 760, 152, 678, 4, 567, 73, 134, 331, 1008, 710, 28, 20, 448, 78, 27, 523, 379, 316, 912, 855, 1011, 920, 458, 1033, 339, 650, 420, 456, 326, 863, 1034, 851, 706, 598, 894, 90, 959, 629, 208, 430, 1056, 450, 306, 104, 592, 233, 66, 856, 579, 91, 783, 345, 414, 672, 870, 641, 860, 919, 360, 457, 804, 147, 436, 752, 494, 1010, 219, 421, 627, 556, 310, 849, 10, 826, 950, 321, 5, 60, 891, 941, 168, 903, 382, 695, 7, 973, 23, 1023, 827, 1036, 115, 226, 489, 40, 786, 831, 419, 1042, 991, 342, 465, 536, 618, 264, 19, 182, 438, 647, 1053, 864, 18, 674, 307, 644, 399, 751, 126, 951, 901, 915, 120, 257, 61, 2, 12, 965, 439, 947, 424, 21, 693, 600, 453, 846, 250, 676, 407, 304, 150, 472, 734, 1024, 610, 869, 818, 802, 756, 585, 890, 466, 183, 349, 211, 808, 773, 336, 37, 772, 907, 482, 17, 13, 609, 89, 935, 299, 582, 484, 467, 978, 943, 400, 359, 325, 148, 594, 1007, 1039, 117, 383, 344, 835, 485, 285, 970, 468, 55, 703, 937, 210, 327, 737, 668, 1043, 329, 1041, 1012, 944, 493, 94, 87, 588, 815, 558, 561, 266, 985, 763, 768, 1058, 1029, 933, 64, 713, 531, 365, 303, 575, 437, 46, 508, 393, 165, 744, 391, 135, 1048, 116, 124, 378, 528, 916, 673, 874, 212, 301, 517, 932, 1017, 781, 825, 1050, 202, 953, 463, 77, 654, 0, 256, 1035, 377, 461, 197, 788, 248, 375, 72, 568, 844, 159, 1054, 616, 151, 882, 717, 410, 613, 237, 281, 9, 736, 735, 829, 685, 497, 267, 634, 1020, 720, 770, 822, 677, 1031, 368, 888, 868, 573, 340, 643, 889, 928, 483, 341, 511, 172, 294, 145, 996, 282, 1001, 287, 93, 952, 333, 904, 372, 405, 853, 155, 721, 776, 691, 745, 74, 542, 272, 566, 799, 278, 129, 277, 942, 696, 370, 841, 261, 123, 537, 236, 899, 352, 121, 812, 265, 761, 684, 662, 63, 757, 670, 490, 702, 330, 308, 322, 990, 187, 949, 298, 552, 103, 452, 892, 687, 99, 426, 200, 762, 526, 249, 633, 657, 488, 897, 247, 158, 180, 65, 780, 931, 708, 845, 295, 884, 347, 967, 86, 645, 816, 412, 139, 648, 320, 532, 622, 675, 697, 832, 603, 1055, 181, 95, 213, 48, 486, 559, 576, 607, 738, 309, 232, 280, 522, 42, 198, 731, 798, 503, 269, 873, 312, 541, 987, 26, 966, 539, 474, 177, 390, 805, 283, 194, 1018, 469, 189, 380, 481, 217, 759, 373, 599, 394, 132, 957, 994, 337, 409, 714, 929, 792, 969, 297, 136, 939, 193, 319, 679, 771, 871, 354, 296, 606, 432, 255, 470, 847, 922, 646, 656, 216, 498, 449, 946, 824, 441, 910, 292, 505, 363, 33, 779, 293, 31, 712, 502, 945, 446, 917, 56, 982, 914, 140, 554, 574, 930, 602, 114, 1059, 803, 663, 785, 833, 711, 963, 893, 639, 392, 909, 510, 680, 840, 367, 154, 418, 67, 521, 659, 570, 758, 979, 1022, 651, 252, 608, 1032, 442, 587, 479, 1019, 253, 291, 551, 704, 652, 348, 195, 509, 813, 478, 204, 142, 225, 398, 553, 876, 886, 625, 705, 878, 259, 715, 767, 240, 381, 243, 149, 369, 53, 68, 411, 612, 512, 975, 141, 1051, 621, 789, 513, 62, 455, 276, 661, 475, 105, 1037, 908, 122, 535, 795, 43, 580, 716, 51, 167, 862, 462, 30, 839, 153, 428, 1025, 491, 911, 581, 936, 875, 81, 258, 814, 385, 15, 923, 215, 96, 545, 403, 611, 179, 593, 235, 387, 220, 655, 550, 604, 1044, 434, 314, 632, 471, 583, 206, 8, 518, 188, 110, 689, 431, 865, 234, 842, 263, 422, 895, 429, 640, 819, 185, 32, 565, 246, 254, 473, 617, 41, 79, 940, 500, 506, 741, 218, 137, 476, 460, 1016, 997, 302, 111, 1045, 275, 828, 1015, 524, 251, 968, 548, 164, 242, 343, 974, 924, 1028, 850, 288, 205, 284, 1, 82, 743, 351, 790, 315, 1026, 239, 241, 34, 427, 630, 364, 417, 443, 623, 1000, 983, 14, 507, 669, 504, 131, 371, 883, 144, 338, 927, 547, 346, 396, 755, 54, 902, 896, 791, 777, 782, 571, 138, 747, 11, 156, 838, 39, 569, 534, 733, 192, 92, 729, 1049, 564, 435, 753, 1052, 201, 726, 196, 748, 184, 830, 516, 900, 519, 707, 1009, 75, 586, 934, 956, 1003, 305, 384, 887, 107, 101, 913, 324, 811, 477, 877, 834, 683, 597, 289, 222, 861, 514, 47, 809, 389, 157, 402, 1057, 408, 229, 268, 543, 722, 686, 224, 642, 793, 857, 906, 501, 228, 366, 76, 270, 540, 948, 596, 823, 615, 323, 520, 97, 127, 406, 925, 918, 190, 787, 83, 775]
print(a==b)

True
